// Uzbekistan regions and districts data
export interface District {
  id: string
  name: string
}

export interface Region {
  id: string
  name: string
  districts: District[]
}

export const regions: Region[] = [
  {
    id: "tashkent_city",
    name: "Toshkent shahri",
    districts: [
      { id: "bektemir", name: "Bektemir tumani" },
      { id: "chilanzar", name: "Chilonzor tumani" },
      { id: "hamza", name: "Hamza tumani" },
      { id: "mirobod", name: "Mirobod tumani" },
      { id: "mirzo_ulugbek", name: "Mirzo Ulug'bek tumani" },
      { id: "sergeli", name: "Sergeli tumani" },
      { id: "shayxontohur", name: "Shayxontohur tumani" },
      { id: "olmazar", name: "Olmazor tumani" },
      { id: "uchtepa", name: "Uchtepa tumani" },
      { id: "yakkasaray", name: "Yakkasaroy tumani" },
      { id: "yunusobod", name: "Yunusobod tumani" },
    ],
  },
  {
    id: "tashkent_region",
    name: "Toshkent viloyati",
    districts: [
      { id: "bekobod", name: "Bekobod tumani" },
      { id: "bostonliq", name: "Bo'stonliq tumani" },
      { id: "boka", name: "Bo'ka tumani" },
      { id: "chinoz", name: "Chinoz tumani" },
      { id: "qibray", name: "Qibray tumani" },
      { id: "ohangaron", name: "Ohangaron tumani" },
      { id: "olmaliq", name: "Olmaliq shahri" },
      { id: "parkent", name: "Parkent tumani" },
      { id: "pskent", name: "Piskent tumani" },
      { id: "quyi_chirchiq", name: "Quyi Chirchiq tumani" },
      { id: "orta_chirchiq", name: "O'rta Chirchiq tumani" },
      { id: "yuqori_chirchiq", name: "Yuqori Chirchiq tumani" },
      { id: "zangiota", name: "Zangiota tumani" },
      { id: "angren", name: "Angren shahri" },
      { id: "chirchiq", name: "Chirchiq shahri" },
    ],
  },
  {
    id: "andijan",
    name: "Andijon viloyati",
    districts: [
      { id: "andijan_city", name: "Andijon shahri" },
      { id: "andijan_district", name: "Andijon tumani" },
      { id: "asaka", name: "Asaka tumani" },
      { id: "baliqchi", name: "Baliqchi tumani" },
      { id: "boz", name: "Bo'z tumani" },
      { id: "buloqboshi", name: "Buloqboshi tumani" },
      { id: "izboskan", name: "Izboskan tumani" },
      { id: "jalaquduq", name: "Jalaquduq tumani" },
      { id: "xojaobod", name: "Xo'jaobod tumani" },
      { id: "qorgontepa", name: "Qo'rg'ontepa tumani" },
      { id: "marhamat", name: "Marhamat tumani" },
      { id: "oltinqol", name: "Oltinko'l tumani" },
      { id: "paxtaobod", name: "Paxtaobod tumani" },
      { id: "shahrixon", name: "Shahrixon tumani" },
      { id: "ulugnar", name: "Ulug'nor tumani" },
      { id: "xonobod", name: "Xonobod shahri" },
    ],
  },
  {
    id: "bukhara",
    name: "Buxoro viloyati",
    districts: [
      { id: "bukhara_city", name: "Buxoro shahri" },
      { id: "bukhara_district", name: "Buxoro tumani" },
      { id: "gijduvon", name: "G'ijduvon tumani" },
      { id: "jondor", name: "Jondor tumani" },
      { id: "kogon", name: "Kogon tumani" },
      { id: "olot", name: "Olot tumani" },
      { id: "peshku", name: "Peshku tumani" },
      { id: "qorakol", name: "Qorako'l tumani" },
      { id: "qorovulbozor", name: "Qorovulbozor tumani" },
      { id: "romitan", name: "Romitan tumani" },
      { id: "shofirkon", name: "Shofirkon tumani" },
      { id: "vobkent", name: "Vobkent tumani" },
    ],
  },
  {
    id: "fergana",
    name: "Farg'ona viloyati",
    districts: [
      { id: "fergana_city", name: "Farg'ona shahri" },
      { id: "fergana_district", name: "Farg'ona tumani" },
      { id: "beshariq", name: "Beshariq tumani" },
      { id: "bogdod", name: "Bog'dod tumani" },
      { id: "buvayda", name: "Buvayda tumani" },
      { id: "dang_ara", name: "Dang'ara tumani" },
      { id: "furqat", name: "Furqat tumani" },
      { id: "qoshtepa", name: "Qo'shtepa tumani" },
      { id: "quva", name: "Quva tumani" },
      { id: "rishton", name: "Rishton tumani" },
      { id: "sox", name: "So'x tumani" },
      { id: "toshloq", name: "Toshloq tumani" },
      { id: "uchkuprik", name: "Uchko'prik tumani" },
      { id: "uzbekistan", name: "O'zbekiston tumani" },
      { id: "yozyovon", name: "Yozyovon tumani" },
      { id: "qukon", name: "Qo'qon shahri" },
      { id: "margilan", name: "Marg'ilon shahri" },
    ],
  },
  {
    id: "jizzakh",
    name: "Jizzax viloyati",
    districts: [
      { id: "jizzakh_city", name: "Jizzax shahri" },
      { id: "arnasoy", name: "Arnasoy tumani" },
      { id: "baxmal", name: "Baxmal tumani" },
      { id: "dostlik", name: "Do'stlik tumani" },
      { id: "forish", name: "Forish tumani" },
      { id: "gallaorol", name: "G'allaorol tumani" },
      { id: "sharof_rashidov", name: "Sharof Rashidov tumani" },
      { id: "mirzachol", name: "Mirzacho'l tumani" },
      { id: "paxtakor", name: "Paxtakor tumani" },
      { id: "yangiobod", name: "Yangiobod tumani" },
      { id: "zomin", name: "Zomin tumani" },
      { id: "zafarobod", name: "Zafarobod tumani" },
    ],
  },
  {
    id: "kashkadarya",
    name: "Qashqadaryo viloyati",
    districts: [
      { id: "qarshi_city", name: "Qarshi shahri" },
      { id: "chiroqchi", name: "Chiroqchi tumani" },
      { id: "dehqonobod", name: "Dehqonobod tumani" },
      { id: "guzor", name: "G'uzor tumani" },
      { id: "qamashi", name: "Qamashi tumani" },
      { id: "qarshi_district", name: "Qarshi tumani" },
      { id: "kasbi", name: "Kasbi tumani" },
      { id: "kitob", name: "Kitob tumani" },
      { id: "koson", name: "Koson tumani" },
      { id: "mirishkor", name: "Mirishkor tumani" },
      { id: "muborak", name: "Muborak tumani" },
      { id: "nishon", name: "Nishon tumani" },
      { id: "shahrisabz", name: "Shahrisabz tumani" },
      { id: "yakkabog", name: "Yakkabog' tumani" },
    ],
  },
  {
    id: "khorezm",
    name: "Xorazm viloyati",
    districts: [
      { id: "urgench_city", name: "Urganch shahri" },
      { id: "bogot", name: "Bog'ot tumani" },
      { id: "gurlan", name: "Gurlan tumani" },
      { id: "khonqa", name: "Xonqa tumani" },
      { id: "hazorasp", name: "Hazorasp tumani" },
      { id: "khiva", name: "Xiva tumani" },
      { id: "qoshkopir", name: "Qo'shko'pir tumani" },
      { id: "shovot", name: "Shovot tumani" },
      { id: "urgench_district", name: "Urganch tumani" },
      { id: "yangiariq", name: "Yangiariq tumani" },
      { id: "yangibozor", name: "Yangibozor tumani" },
    ],
  },
  {
    id: "namangan",
    name: "Namangan viloyati",
    districts: [
      { id: "namangan_city", name: "Namangan shahri" },
      { id: "chortoq", name: "Chortoq tumani" },
      { id: "chust", name: "Chust tumani" },
      { id: "kosonsoy", name: "Kosonsoy tumani" },
      { id: "mingbuloq", name: "Mingbuloq tumani" },
      { id: "namangan_district", name: "Namangan tumani" },
      { id: "norin", name: "Norin tumani" },
      { id: "pop", name: "Pop tumani" },
      { id: "toraqqorgon", name: "To'raqo'rg'on tumani" },
      { id: "uchqorgon", name: "Uchqo'rg'on tumani" },
      { id: "uychi", name: "Uychi tumani" },
      { id: "yangiqorgon", name: "Yangiqo'rg'on tumani" },
    ],
  },
  {
    id: "navoiy",
    name: "Navoiy viloyati",
    districts: [
      { id: "navoiy_city", name: "Navoiy shahri" },
      { id: "karmana", name: "Karmana tumani" },
      { id: "konimex", name: "Konimex tumani" },
      { id: "navbahor", name: "Navbahor tumani" },
      { id: "nurota", name: "Nurota tumani" },
      { id: "qiziltepa", name: "Qiziltepa tumani" },
      { id: "tomdi", name: "Tomdi tumani" },
      { id: "uchquduq", name: "Uchquduq tumani" },
      { id: "xatirchi", name: "Xatirchi tumani" },
      { id: "zarafshon", name: "Zarafshon shahri" },
    ],
  },
  {
    id: "samarkand",
    name: "Samarqand viloyati",
    districts: [
      { id: "samarkand_city", name: "Samarqand shahri" },
      { id: "bulungur", name: "Bulung'ur tumani" },
      { id: "ishtixon", name: "Ishtixon tumani" },
      { id: "jomboy", name: "Jomboy tumani" },
      { id: "kattaqorgon", name: "Kattaqo'rg'on tumani" },
      { id: "qoshrabot", name: "Qo'shrabot tumani" },
      { id: "narpay", name: "Narpay tumani" },
      { id: "nurobod", name: "Nurobod tumani" },
      { id: "oqdaryo", name: "Oqdaryo tumani" },
      { id: "paxtachi", name: "Paxtachi tumani" },
      { id: "payariq", name: "Payariq tumani" },
      { id: "pastdargom", name: "Pastdarg'om tumani" },
      { id: "samarkand_district", name: "Samarqand tumani" },
      { id: "toyloq", name: "Toyloq tumani" },
      { id: "urgut", name: "Urgut tumani" },
    ],
  },
  {
    id: "sirdarya",
    name: "Sirdaryo viloyati",
    districts: [
      { id: "guliston_city", name: "Guliston shahri" },
      { id: "boyovut", name: "Boyovut tumani" },
      { id: "guliston_district", name: "Guliston tumani" },
      { id: "mirzaobod", name: "Mirzaobod tumani" },
      { id: "oqoltin", name: "Oqoltin tumani" },
      { id: "sardoba", name: "Sardoba tumani" },
      { id: "sayxunobod", name: "Sayxunobod tumani" },
      { id: "sirdaryo_district", name: "Sirdaryo tumani" },
      { id: "xovos", name: "Xovos tumani" },
      { id: "yangiyer", name: "Yangiyer shahri" },
      { id: "shirin", name: "Shirin shahri" },
    ],
  },
  {
    id: "surxondarya",
    name: "Surxondaryo viloyati",
    districts: [
      { id: "termiz_city", name: "Termiz shahri" },
      { id: "angor", name: "Angor tumani" },
      { id: "bandixon", name: "Bandixon tumani" },
      { id: "boysun", name: "Boysun tumani" },
      { id: "denov", name: "Denov tumani" },
      { id: "jarqorgon", name: "Jarqo'rg'on tumani" },
      { id: "qiziriq", name: "Qiziriq tumani" },
      { id: "qumqorgon", name: "Qumqo'rg'on tumani" },
      { id: "muzrabot", name: "Muzrabot tumani" },
      { id: "oltinsoy", name: "Oltinsoy tumani" },
      { id: "sariosiyo", name: "Sariosiyo tumani" },
      { id: "sherobod", name: "Sherobod tumani" },
      { id: "shorchi", name: "Sho'rchi tumani" },
      { id: "termiz_district", name: "Termiz tumani" },
      { id: "uzun", name: "Uzun tumani" },
    ],
  },
  {
    id: "karakalpakstan",
    name: "Qoraqalpog'iston Respublikasi",
    districts: [
      { id: "nukus_city", name: "Nukus shahri" },
      { id: "amudaryo", name: "Amudaryo tumani" },
      { id: "beruniy", name: "Beruniy tumani" },
      { id: "chimboy", name: "Chimboy tumani" },
      { id: "ellikqala", name: "Ellikqal'a tumani" },
      { id: "kegeyli", name: "Kegeyli tumani" },
      { id: "kungirot", name: "Qo'ng'irot tumani" },
      { id: "moynaq", name: "Mo'ynoq tumani" },
      { id: "nukus_district", name: "Nukus tumani" },
      { id: "qonlikol", name: "Qanliko'l tumani" },
      { id: "qoraozak", name: "Qorao'zak tumani" },
      { id: "shumanay", name: "Shumanay tumani" },
      { id: "taxtakopir", name: "Taxtako'pir tumani" },
      { id: "tortkol", name: "To'rtko'l tumani" },
      { id: "xojeli", name: "Xo'jayli tumani" },
    ],
  },
]

export function getRegionByName(name: string): Region | undefined {
  return regions.find((r) => r.name === name)
}

export function getDistrictsByRegion(regionName: string): District[] {
  const region = getRegionByName(regionName)
  return region?.districts || []
}
